final List<String> productNames = [
    "Pineapple",
    "Tuna",
    "Quinoa",
    "Couscous",
    "Grapes",
    "Canola oil",
    "Water",
    "Jam",
    "Chicken",
    "Cookies",
    "Walnuts",
    "Bread",
    "Cinnamon",
    "Pepper",
    "Scallops",
    "Cheese",
    "Tea",
    "Butter",
    "Barley",
    "Plum",
    "Strawberry",
    "Soy sauce",
    "Blueberry",
    "Crab",
    "Lobster",
    "Rice cakes",
    "Coconut oil",
    "Muesli",
    "Margarine",
    "Coconut water",
    "Juice",
    "Rice"
  ];